CREATE TABLE dealers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  slug VARCHAR(190) UNIQUE NOT NULL,
  phone VARCHAR(60),
  logo_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
  id VARCHAR(80) PRIMARY KEY,
  dealer_id BIGINT REFERENCES dealers(id) ON DELETE CASCADE,
  name VARCHAR(190) NOT NULL,
  category VARCHAR(120),
  unit VARCHAR(40),
  price NUMERIC(14,2) DEFAULT 0,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE proposals (
  id VARCHAR(80) PRIMARY KEY,
  dealer_id BIGINT REFERENCES dealers(id) ON DELETE SET NULL,
  customer_name VARCHAR(190) NOT NULL,
  customer_phone VARCHAR(60),
  project_name VARCHAR(190),
  product_name VARCHAR(190),
  product_unit VARCHAR(40),
  quantity NUMERIC(14,3) DEFAULT 0,
  subtotal NUMERIC(14,2) DEFAULT 0,
  vat NUMERIC(14,2) DEFAULT 0,
  total NUMERIC(14,2) DEFAULT 0,
  currency VARCHAR(10) DEFAULT 'TRY',
  status VARCHAR(30) DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
