import type { LangCode } from '@/types/offer';
export const LANG_META: Record<LangCode,{name:string;flag:string;dir:'ltr'|'rtl';locale:string}>={
 tr:{name:'Türkçe',flag:'🇹🇷',dir:'ltr',locale:'tr-TR'}, en:{name:'English',flag:'🇬🇧',dir:'ltr',locale:'en-US'}, de:{name:'Deutsch',flag:'🇩🇪',dir:'ltr',locale:'de-DE'}, fr:{name:'Français',flag:'🇫🇷',dir:'ltr',locale:'fr-FR'}, ru:{name:'Русский',flag:'🇷🇺',dir:'ltr',locale:'ru-RU'}, ar:{name:'العربية',flag:'🇸🇦',dir:'rtl',locale:'ar-SA'}
};
export const DICT: Record<LangCode,Record<string,string>>={
 tr:{title:'MT Altaş Hesaplayıcı',sub:'6 dilli profesyonel teklif ve maliyet hesaplama SaaS başlangıcı',area:'Alan (m²)',unit:'Birim fiyat',labor:'İşçilik',shipping:'Nakliye',vat:'KDV oranı',calc:'Hesapla',subtotal:'Ara toplam',vatTotal:'KDV',total:'Genel toplam',offer:'Teklif Belgesi İndir',company:'Firma paneli',customer:'Müşteri',project:'Proje',note:'Kurumsal teklif altyapısı'},
 en:{title:'MT Altas Calculator',sub:'6-language professional quotation and cost calculation SaaS starter',area:'Area (m²)',unit:'Unit price',labor:'Labor',shipping:'Shipping',vat:'VAT rate',calc:'Calculate',subtotal:'Subtotal',vatTotal:'VAT',total:'Grand total',offer:'Download quotation',company:'Company panel',customer:'Customer',project:'Project',note:'Corporate quotation infrastructure'},
 de:{title:'MT Altas Rechner',sub:'6-sprachiger SaaS-Start für professionelle Angebote und Kostenberechnung',area:'Fläche (m²)',unit:'Einheitspreis',labor:'Arbeit',shipping:'Transport',vat:'MwSt.-Satz',calc:'Berechnen',subtotal:'Zwischensumme',vatTotal:'MwSt.',total:'Gesamtsumme',offer:'Angebot herunterladen',company:'Firmenpanel',customer:'Kunde',project:'Projekt',note:'Professionelle Angebotsinfrastruktur'},
 fr:{title:'Calculateur MT Altas',sub:'Base SaaS en 6 langues pour devis et calcul professionnel des coûts',area:'Surface (m²)',unit:'Prix unitaire',labor:'Main-d’œuvre',shipping:'Transport',vat:'Taux TVA',calc:'Calculer',subtotal:'Sous-total',vatTotal:'TVA',total:'Total général',offer:'Télécharger le devis',company:'Panneau entreprise',customer:'Client',project:'Projet',note:'Infrastructure de devis professionnelle'},
 ru:{title:'Калькулятор MT Altas',sub:'SaaS-старт на 6 языках для профессиональных расчетов и предложений',area:'Площадь (м²)',unit:'Цена за единицу',labor:'Работа',shipping:'Доставка',vat:'Ставка НДС',calc:'Рассчитать',subtotal:'Промежуточный итог',vatTotal:'НДС',total:'Итого',offer:'Скачать предложение',company:'Панель компании',customer:'Клиент',project:'Проект',note:'Корпоративная инфраструктура предложений'},
 ar:{title:'حاسبة MT Altas',sub:'بداية SaaS احترافية بست لغات للحسابات وعروض الأسعار',area:'المساحة (م²)',unit:'سعر الوحدة',labor:'العمل',shipping:'النقل',vat:'نسبة الضريبة',calc:'احسب',subtotal:'المجموع الفرعي',vatTotal:'الضريبة',total:'الإجمالي',offer:'تنزيل عرض السعر',company:'لوحة الشركة',customer:'العميل',project:'المشروع',note:'بنية احترافية لعروض الأسعار'}
};
export function t(lang:LangCode,key:string){return DICT[lang]?.[key]||DICT.tr[key]||key}
