'use client';
import {useMemo,useState} from 'react';
import {calculateOffer,money} from '@/lib/calc/mtaCalcCore';
import {useMtaLang} from '@/lib/i18n/useMtaLang';
import {LANG_META} from '@/lib/i18n/dictionaries';
import {downloadProposal} from '@/lib/pdf/proposalPdf';
export default function MtaSaasApp(){const {lang,setLang,T,langs,meta}=useMtaLang(); const [area,setArea]=useState(100); const [unitPrice,setUnitPrice]=useState(350); const [laborPrice,setLabor]=useState(5000); const [shipping,setShipping]=useState(3500); const [vatRate,setVatRate]=useState(0.20); const result=useMemo(()=>calculateOffer({area,unitPrice,laborPrice,shipping,vatRate}),[area,unitPrice,laborPrice,shipping,vatRate]); const locale=meta.locale; return <main dir={meta.dir} className="min-h-screen bg-[#0f1724] px-4 py-6 text-white"><section className="mx-auto max-w-6xl rounded-3xl border border-white/10 bg-[#182234] p-5 shadow-2xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs font-bold text-amber-100">MT Altaş SaaS</span><h1 className="mt-3 text-3xl font-black">{T('title')}</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">{T('sub')}</p></div><select className="rounded-xl border border-white/10 bg-white px-3 py-2 text-sm font-bold" value={lang} onChange={e=>setLang(e.target.value as any)}>{langs.map(l=><option key={l} value={l}>{LANG_META[l].flag} {LANG_META[l].name}</option>)}</select></div><div className="mt-6 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-white/10 bg-[#1f2a3d] p-4"><h2 className="text-lg font-extrabold">{T('company')}</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label={T('area')} value={area} setValue={setArea}/><Field label={T('unit')} value={unitPrice} setValue={setUnitPrice}/><Field label={T('labor')} value={laborPrice} setValue={setLabor}/><Field label={T('shipping')} value={shipping} setValue={setShipping}/><Field label={T('vat')} value={vatRate*100} setValue={(v)=>setVatRate(v/100)}/></div></div><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-4"><p className="text-sm font-bold text-emerald-100">{T('note')}</p><div className="mt-5 space-y-3 text-sm"><Row k={T('subtotal')} v={money(result.subtotal,locale)}/><Row k={T('vatTotal')} v={money(result.vat,locale)}/><Row k={T('total')} v={money(result.total,locale)} strong/></div><button onClick={()=>downloadProposal(lang,result)} className="mt-5 w-full rounded-2xl bg-emerald-500 px-4 py-3 font-black text-white hover:bg-emerald-400">{T('offer')}</button></div></div></section></main>}
function Field({label,value,setValue}:{label:string;value:number;setValue:(v:number)=>void}){return <label className="block"><span className="mb-1 block text-xs font-bold text-slate-300">{label}</span><input type="number" value={value} onChange={e=>setValue(Number(e.target.value))} className="h-12 w-full rounded-xl border border-white/10 bg-white px-3 text-sm font-bold"/></label>}
function Row({k,v,strong}:{k:string;v:string;strong?:boolean}){return <div className="flex items-center justify-between gap-3 border-b border-white/10 pb-2"><span className="text-slate-300">{k}</span><b className={strong?'text-xl text-white':'text-white'}>{v}</b></div>}
